### ISSUE TITLE
String concatenation breaks with math 

### ISSUE THREAD

**Issue by IAmCheeseman** [BergerAPI/ACL#11]
Was making a fibbnaci program, wrote this:
`println("iter #" + i + 1 + ": " + x)`
Output was:
```
iter #01: 1
iter #11: 1
iter #21: 2
...
```
I could fix it by doing this instead:
`println("iter #" + (i + 1) + ": " + x)`

**Comment by BergerAPI** [comment]
This is sadly not fixable by us.
