### ISSUE TITLE
Import entire folders

### ISSUE THREAD

**Issue by Dot32Dev** [BergerAPI/ACL#6]
**Is your feature request related to a problem? Please describe.**
If I wish to import every file from a folder, i would have to write
```go
import folder/foo.acl
import folder/bar.acl
import folder/fizz.acl
import folder/baz.acl
```

**Describe the solution you'd like**
If you import a folder, it automatically walks the folder and imports every .acl from within
The above example would instead be written as
```go
import folder
```

**Describe alternatives you've considered**
Perhaps it would make sense to instead 
```go
import folder/*.acl
```
Perhaps this could be added in tandem and have `import folder` simply be syntax suger, but that would require more complex parsing of the import string, and may simply be unnecessary. In this example, the *.acl approach would be cumbersome.
```go
import outerFolder
```
versus;
```
import outerFolder/*.acl
import outerFolder/*/*.acl #You have to specify how many folders deep a file is that you're looking for
```

**Additional context**
std could simply be a folder of the standard folders, importing specifically math could be 
```go
import std/math.acl
```
I feel this to be a clean approach

**Comment by BergerAPI** [comment]
The approach without `*.acl` is probably the better one, and might be even integrated in further versions of ACL.

**Comment by IAmCheeseman** [comment]
> The approach without `*.acl` is probably the better one, and might be even integrated in further versions of ACL.

imo the .acl makes it clear whether what you're importing is a folder or a file
