### ISSUE TITLE
Add switch statement

### ISSUE THREAD

**Issue by IAmCheeseman** [BergerAPI/ACL#9]
with either of these syntaxes:
```js
switch h {
    case "h" {
        println(h)
    }
    default {}
}
```
or
```js
switch h {
    case "h":
        println(h)
    default:
        code()
}
```

**Comment by Dot32Dev** [comment]
I like them the first syntax for the switch statement, but perhaps the `:` syntax could be for single liners
Given that we can do `let variable = if {}` it also would make sense to have `let variable = switch {} `
